### ISSUE TITLE
Reproducing Pose Results

### ISSUE THREAD

**Issue by truncs** [Uehwan/SimVODIS#2]
Hi @Uehwan, I am trying to reproduce the pose results in the SimVODIS paper but I found there are couple of issues while running the script - 

- When generating the triplets for the 00000 image id it generates ./kitti_odom/sequences/09/image_2/-00001.jpg, which causes it to error out
- When trying to load the e2e_mask_rcnn_R_50_FPN_1x.yaml it errors out with "RuntimeError: cannot perform reduction function max on tensor with no elements because the operation does not have an identity"

Also I am trying to understand the input size for the pose decoder, in the code below

```
 self.vo_conv1 = conv(256 * 3, 256, kernel_size=7)
```

The 3 comes from the fact that three frames are used to get the R, T? How would this work with let's say if 2 frames are used? I assume that the network would have to be retrained?

Is there an example with the output of RCNN, depth and pose together?

**Comment by Uehwan** [comment]
1. For the first issue, you need to erase the first lines of the following files:
- SimVODIS/splits/odom/test_files_09.txt
- SimVODIS/splits/odom/test_files_10.txt

2. I'm not sure about the runtime error. Did you set up the running environment as specified? I have not experienced the error you mentioned though I ran the script on multiple devices.

3. If you want to use 2 frames for pose estimation, you need to modify parts of the code and retrain the networks. When I used SimVODIS for pose estimation, I fed 3 frames, used the first pose output (the pose between first and second frames), and ditched the second pose (the pose between second and third frames).

**Comment by truncs** [comment]
Thanks for the reply. The suggestion to remove the first line did work! I am trying to get an absolute estimation of the trajectory  and I am finding it hard to set the right scale. 

This is the trajectory with using the scale computation in ate

![map](https://user-images.githubusercontent.com/157234/103595030-39bf1700-4eaf-11eb-87e7-8485a24fbaa7.png)

And it just renders a dot if I set it using just 1 ground truth point. Any thoughts on how to plot the trajectory for visual comparison? Attaching code for reference below

```
poses = np.load('/poses.npy')
pred_xyz = dump_xyz(poses)


with open('/data/kitti_odom/poses/09.txt') as f:
    annotations = f.readlines()

def getAbsoluteScale(annotations, frame_id):  #specialized for KITTI odometry dataset

    if frame_id == 0:
        return 0, 0, 0, 0

    ss = annotations[frame_id-1].strip().split()
    x_prev = float(ss[3])
    y_prev = float(ss[7])
    z_prev = float(ss[11])
    ss = annotations[frame_id].strip().split()
    x = float(ss[3])
    y = float(ss[7])
    z = float(ss[11])

    return np.sqrt((x - x_prev)*(x - x_prev) + (y - y_prev)*(y - y_prev) + (z - z_prev)*(z - z_prev)), x, y, z


traj = np.zeros((600,600,3), dtype=np.uint8)
x, y, z = 0, 0, 0

for i in range(len(annotations)):

    scale, true_x, true_y, true_z = getAbsoluteScale(annotations, i)
    
    if i > 0:
        gtruth_xyz = np.array([true_x, true_y, true_z])
        scale = np.sum(gtruth_xyz * pred_xyz[i]) / np.sum(pred_xyz[i] ** 2)

    xyz = pred_xyz[i] * scale
    print(xyz, true_x, true_y, true_z)
    x, y, z = xyz[0], xyz[1], xyz[2]
    
    draw_x, draw_y = int(x)+290, int(z)+90
    true_x, true_y = int(true_x)+290, int(true_z)+90
    
    cv2.circle(traj, (draw_x,draw_y), 1, (i*255/4540,255-i*255/4540,0), 1)
    cv2.circle(traj, (true_x,true_y), 1, (0,0,255), 2)
    cv2.rectangle(traj, (10, 20), (600, 60), (0,0,0), -1)
    text = "Coordinates: x=%2fm y=%2fm z=%2fm image=%d"%(x,y,z, i)
    cv2.putText(traj, text, (20,40), cv2.FONT_HERSHEY_PLAIN, 1, (255,255,255), 1, 8)

cv2.imwrite('map.png', traj)
```

Btw if Github issues is not the right medium then I will be happy to email you directly. Thanks!

**Comment by Uehwan** [comment]
Thank you for your attention.

You could use the following module to draw the trajectory and calculate ATE: https://github.com/MichaelGrupp/evo
We actually used the above module to draw trajectories :)

**Comment by linpeisensh** [comment]
@chickenbestlover 
Hello!

Have you solve "RuntimeError: cannot perform reduction function max on tensor with no elements because the operation does not have an identity"?

If yes, how do you solve this error?

**Comment by linpeisensh** [comment]
@truncs 
Hello!

Have you solve "RuntimeError: cannot perform reduction function max on tensor with no elements because the operation does not have an identity"?

If yes, how do you solve this error?

**Comment by linpeisensh** [comment]
@Uehwan 
Thank you for your excellent work!
I want to know if there is a method to save the trajectory.txt file which can be used to https://github.com/MichaelGrupp/evo.

**Comment by DaddyWesker** [comment]
> When trying to load the e2e_mask_rcnn_R_50_FPN_1x.yaml it errors out with "RuntimeError: cannot perform reduction function max on tensor with no elements because the operation does not have an identity"

I've met the same problem. In the file maskrcnn_benchmark/utils/checkpoint.py file there is a line
`checkpoint = self._convert_checkpoint(checkpoint_old)`
After this line, checkpoint is empty. That is why you'll get this error. I've bypassed it by not entering convert_checkpoint.  Not sure if it is a right decision.
