### ISSUE TITLE
How to save trajectory.txt that can be used with tool https://github.com/MichaelGrupp/evo?

### ISSUE THREAD

**Issue by linpeisensh** [Uehwan/SimVODIS#3]
Hi, @Uehwan
Thank you for your excellent work!
Could you tell me how to save trajectory.txt that can be used with tool https://github.com/MichaelGrupp/evo?

**Comment by Uehwan** [comment]
Hi, thank you for your attention!

1) You can pass three images to the pre-trained pose net at a time.
2) Then, you'll get two pose results one for t-1 => t and the other for t+1 => t
3) Just save the first pose vector to trajectory.txt

I'm rewriting the code for it and it'll be released soon here or in another repo :)
